main:
  - name: About
    url: '#about'
    weight: 1
  - name: CV
    url: 'yash-lala-resume.pdf'
    weight: 2
  # TODO: Can we switch the URL to /resources instead?
  - name: Resources
    url: /docs/
    weight: 3
  # - name: Posts
  #   url: /posts/
  #   weight: 2
