# Basic config
baseURL = "https://yashlala.com"
title = "Yash Lala"
copyright = "© Yash Lala"
mainSections = [ "blog", "cv", "resources" ]

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

languageCode = "en"
defaultContentLanguage = "en"
services.rss.limit = 42

# https://github.com/gohugoio/hugo/issues/12152
capitalizeListTitles = false

# Yash: I'm not sure what this does yet. 
# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[pagination]
    pagerSize = 16

[taxonomies]
    tag = "tags"

[permalinks]
    blog = "/blog/:year/:slugorcontentbasename/"
    tags = "/tags/:slug"

[params]
    title = "Yash Lala"
    description = "Yash Lala's Personal Website"
    favicon = "img/favicon.png"
    dateFormat = "2006-01-02"

[params.author]
    name = "Yash Lala"
    email = "yash.lala@yale.edu"

[[menu.main]]
    name = "About Me"
    pageRef = "/"
    weight = 10

[[menu.main]]
    name = "Research"
    pageRef = "/todo"
    weight = 20

[[menu.main]]
    name = "CV"
    url = "/resume.pdf"
    weight = 30

[[menu.main]]
    name = "Blog"
    pageRef = "/blog"
    weight = 40


[[menu.main]]
    name = "Vault"
    pageRef = "/vault"
    weight = 50

# Generate RSS for home only.
[outputs]
    section = ["html"]
    taxonomy = ["html"]
    term = ["html"]

[markup.goldmark.renderer]
    unsafe = true

# set toc start and end levels
[markup.tableOfContents]
    startLevel = 2
    endLevel = 3

# configure code highlighting
[markup.highlight]
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "catppuccin-mocha"
