# Basic config
baseURL = "https://yashlala.com"
theme = "hugo-simple"
languageCode = "en"
defaultContentLanguage = "en"
title = "Yash Lala"
copyright = "© 2025 Yash Lala"
mainSections = ["blog"]

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# https://github.com/gohugoio/hugo/issues/12152
capitalizeListTitles = false

# Yash: I'm not sure what this does yet. 
# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
disableKinds = ["taxonomy"]
# ignoreErrors = ["error-disable-taxonomy"]
[taxonomies]
tag = "tags"

[permalinks]
blog = "/blog/:year/:slugorcontentbasename/"
tags = "/blog/tags/:slug"

# allow raw html in markdown
[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
# set toc start and end levels
startLevel = 2
endLevel = 3

# configure code highlighting
[markup.highlight]
lineNos = true
lineNumbersInTable = false
noClasses = true
style = "catppuccin-mocha"

[params]
title = "Yash Lala"
description = "Yash Lala's Personal Website"
favicon = "img/favicon.png"
dateFormat = "2006-01-02"
hideMadeWithLine = false
hideRSSLink = false

[params.author]
name = "Yash Lala"
email = "yash.lala@yale.edu"

[[menu.main]]
name = "Home"
pageRef = "/"
weight = 10

[[menu.main]]
name = "Blog"
pageRef = "/blog"
weight = 20

[services.rss]
limit = 42

[pagination]
pagerSize = 16

# Generate RSS for home only.
[outputs]
section = ["html"]
taxonomy = ["html"]
term = ["html"]
